apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
        dt.owner: devopsteam
    spec:
      containers:
        - name: manager
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/manager:8831949
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_PREFIX
              value: "manager"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: dynatrace-envs
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
    - name: http
      port: 8080
      targetPort: 8080
